import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import Navbar from '@/components/ui/navbar'
import { Toaster } from 'sonner'

import { ClerkProvider, SignIn, SignedIn, SignedOut } from '@clerk/nextjs'
import { clerkClient } from '@/lib/clerk-client'
import { Button } from '@/components/shadcn-ui/button'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <SignedOut>
            <div className="flex h-screen w-screen items-center justify-center">
              <SignIn routing="hash" />
            </div>
          </SignedOut>

          <SignedIn>
            <Providers>
              <div className="flex max-h-screen min-h-screen flex-col gap-10 px-10 py-5 pb-5">
                {/* FIX NAVBAR LAYOUT */}
                {/* 
                    <UserButton showName />
                    <Providers>{children}</Providers>
                  */}
                <Navbar />
                <div className="flex flex-grow basis-0">{children}</div>
              </div>
            </Providers>
          </SignedIn>

          <Toaster richColors />
        </ClerkProvider>
      </body>
    </html>
  )
}
