name: Team_Quaternary_CI_Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Cache node modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: application/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('application/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: application

      # Step 5: Run vulnerability scan (npm audit)
      - name: Run vulnerability scan (npm audit)
        run: npm audit --production
        working-directory: application

      # Step 6: Authenticate Snyk CLI
      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Step 7: Run Snyk vulnerability scan
      - name: Run Snyk vulnerability scan
        uses: snyk/actions@v0.4.0  # Use the latest stable v1 version
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      # Step 8: Build the project (Uncomment if needed)
      # - name: Build project
      #   run: npm run build
      #   working-directory: application

      # Step 9: Upload build artifacts (Uncomment if needed)
      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: nextjs-build
      #     path: application/.next
