name: CI for Next.js App

on:
  push:
    branches:
      - CI/Pipeline  # Run on every push to the CI/Pipeline branch
  pull_request:
    branches:
      - CI/Pipeline  # Run on every PR to the CI/Pipeline branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set working directory
        run: cd application  # Change to the directory containing package.json

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Match local Node.js version

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: application/node_modules  # Update path to node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('application/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: /application  # Set working directory for npm install

      - name: Run linter
        run: npm run lint
        working-directory: /application  # Set working directory for linting

      - name: Run tests
        run: npm run test
        working-directory: /application  # Set working directory for tests

      - name: Build project
        run: npm run build
        working-directory: /application  # Set working directory for building

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: application/.next  # Update path to build output folder
